
pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t order-service ./order-service'
                sh 'docker build -t payment-service ./payment-service'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker-compose -f devops/docker/docker-compose.yml up -d'
            }
        }
    }
}
